/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PresentacionClientes;

import encapsulamiento.EncapsulamientoClientes;
import negocio.NegocioClientes;

/**
 *
 * @author Joakim
 */
public class CrearCliente extends javax.swing.JFrame {

    /**
     * Creates new form CrearNivel
     */
    public CrearCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblresultado = new javax.swing.JLabel();
        txttelefono = new RSMaterialComponent.RSTextFieldIconOne();
        txtdireccion = new RSMaterialComponent.RSTextFieldIconOne();
        txtsueldo = new RSMaterialComponent.RSTextFieldIconOne();
        txtnombre = new RSMaterialComponent.RSTextFieldIconOne();
        txtempresa = new RSMaterialComponent.RSTextFieldIconOne();
        txtcargo = new RSMaterialComponent.RSTextFieldIconOne();
        txtcorre = new RSMaterialComponent.RSTextFieldIconOne();
        btnañadir = new RSMaterialComponent.RSButtonMaterialIconOne();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(205, 84, 54));
        setForeground(java.awt.Color.darkGray);

        lblresultado.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblresultado.setText("Resultado");

        txttelefono.setForeground(new java.awt.Color(0, 51, 102));
        txttelefono.setBorderColor(new java.awt.Color(0, 51, 102));
        txttelefono.setColorIcon(new java.awt.Color(0, 51, 102));
        txttelefono.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PHONE);
        txttelefono.setPlaceholder("Telefono");

        txtdireccion.setForeground(new java.awt.Color(0, 51, 102));
        txtdireccion.setBorderColor(new java.awt.Color(0, 51, 102));
        txtdireccion.setColorIcon(new java.awt.Color(0, 51, 102));
        txtdireccion.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        txtdireccion.setPlaceholder("Direccion");

        txtsueldo.setForeground(new java.awt.Color(0, 51, 102));
        txtsueldo.setBorderColor(new java.awt.Color(0, 51, 102));
        txtsueldo.setColorIcon(new java.awt.Color(0, 51, 102));
        txtsueldo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MONETIZATION_ON);
        txtsueldo.setPlaceholder("Sueldo");

        txtnombre.setForeground(new java.awt.Color(0, 51, 102));
        txtnombre.setBorderColor(new java.awt.Color(0, 51, 102));
        txtnombre.setColorIcon(new java.awt.Color(0, 51, 102));
        txtnombre.setPlaceholder("Nombre");
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txtempresa.setForeground(new java.awt.Color(0, 51, 102));
        txtempresa.setBorderColor(new java.awt.Color(0, 51, 102));
        txtempresa.setColorIcon(new java.awt.Color(0, 51, 102));
        txtempresa.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EQUALIZER);
        txtempresa.setPlaceholder("Empresa");

        txtcargo.setForeground(new java.awt.Color(0, 51, 102));
        txtcargo.setBorderColor(new java.awt.Color(0, 51, 102));
        txtcargo.setColorIcon(new java.awt.Color(0, 51, 102));
        txtcargo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.WORK);
        txtcargo.setPlaceholder("Cargo");

        txtcorre.setForeground(new java.awt.Color(0, 51, 102));
        txtcorre.setBorderColor(new java.awt.Color(0, 51, 102));
        txtcorre.setColorIcon(new java.awt.Color(0, 51, 102));
        txtcorre.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MAIL);
        txtcorre.setPlaceholder("Correo");

        btnañadir.setBackground(new java.awt.Color(0, 51, 102));
        btnañadir.setText(" Añadir");
        btnañadir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        btnañadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnañadirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setForeground(new java.awt.Color(0, 51, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Añadir Cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblresultado)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtsueldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtcargo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtempresa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtdireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txttelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtcorre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnañadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcorre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnañadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblresultado)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btnañadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnañadirActionPerformed
        EncapsulamientoClientes n1 = new EncapsulamientoClientes();

        n1.setNombres(txtnombre.getText());
        n1.setCorreo(txtcorre.getText());
        n1.setDireccion(txtdireccion.getText());
        int rtelefono=Integer.parseInt(txttelefono.getText());
        n1.setTelefono(rtelefono);
        n1.setEmpresa(txtempresa.getText());
        n1.setCargo(txtcargo.getText());
        int rsueldo=Integer.parseInt(txtsueldo.getText());
        n1.setSueldo(rsueldo);

        NegocioClientes n2 = new NegocioClientes();

        String resultado = n2.crearCliente(n1);
        lblresultado.setText(resultado);
    }//GEN-LAST:event_btnañadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne btnañadir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblresultado;
    private RSMaterialComponent.RSTextFieldIconOne txtcargo;
    private RSMaterialComponent.RSTextFieldIconOne txtcorre;
    private RSMaterialComponent.RSTextFieldIconOne txtdireccion;
    private RSMaterialComponent.RSTextFieldIconOne txtempresa;
    private RSMaterialComponent.RSTextFieldIconOne txtnombre;
    private RSMaterialComponent.RSTextFieldIconOne txtsueldo;
    private RSMaterialComponent.RSTextFieldIconOne txttelefono;
    // End of variables declaration//GEN-END:variables
}
