/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PresentacionClientes;

import encapsulamiento.EncapsulamientoClientes;
import javax.swing.JOptionPane;
import negocio.NegocioClientes;

/**
 *
 * @author Joakim
 */
public class editarCliente extends javax.swing.JFrame {

    /**
     * Creates new form editarNivel
     */
    public editarCliente() {
        initComponents();
    }
public  int id;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltIID = new javax.swing.JLabel();
        lblrID = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelIcon1 = new necesario.LabelIcon();
        txtcorre = new RSMaterialComponent.RSTextFieldIconOne();
        txttelefono = new RSMaterialComponent.RSTextFieldIconOne();
        txtdireccion = new RSMaterialComponent.RSTextFieldIconOne();
        txtnombre = new RSMaterialComponent.RSTextFieldIconOne();
        txtempresa = new RSMaterialComponent.RSTextFieldIconOne();
        txtcargo = new RSMaterialComponent.RSTextFieldIconOne();
        txtsueldo = new RSMaterialComponent.RSTextFieldIconOne();
        btneditar = new RSMaterialComponent.RSButtonMaterialIconOne();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbltIID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltIID.setText("ID:");

        lblrID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblrID.setText("jLabel1");

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setForeground(new java.awt.Color(0, 51, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Editar Cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        labelIcon1.setForeground(new java.awt.Color(0, 51, 102));
        labelIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_BOX);

        txtcorre.setForeground(new java.awt.Color(0, 51, 102));
        txtcorre.setText("correo");
        txtcorre.setBorderColor(new java.awt.Color(0, 51, 102));
        txtcorre.setColorIcon(new java.awt.Color(0, 51, 102));
        txtcorre.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MAIL);

        txttelefono.setForeground(new java.awt.Color(0, 51, 102));
        txttelefono.setText("telefono");
        txttelefono.setBorderColor(new java.awt.Color(0, 51, 102));
        txttelefono.setColorIcon(new java.awt.Color(0, 51, 102));
        txttelefono.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PHONE);

        txtdireccion.setForeground(new java.awt.Color(0, 51, 102));
        txtdireccion.setText("direccion");
        txtdireccion.setBorderColor(new java.awt.Color(0, 51, 102));
        txtdireccion.setColorIcon(new java.awt.Color(0, 51, 102));
        txtdireccion.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);

        txtnombre.setForeground(new java.awt.Color(0, 51, 102));
        txtnombre.setText("Nombre");
        txtnombre.setBorderColor(new java.awt.Color(0, 51, 102));
        txtnombre.setColorIcon(new java.awt.Color(0, 51, 102));
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txtempresa.setForeground(new java.awt.Color(0, 51, 102));
        txtempresa.setText("empresa");
        txtempresa.setBorderColor(new java.awt.Color(0, 51, 102));
        txtempresa.setColorIcon(new java.awt.Color(0, 51, 102));
        txtempresa.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EQUALIZER);

        txtcargo.setForeground(new java.awt.Color(0, 51, 102));
        txtcargo.setText("cargo");
        txtcargo.setBorderColor(new java.awt.Color(0, 51, 102));
        txtcargo.setColorIcon(new java.awt.Color(0, 51, 102));
        txtcargo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.WORK);

        txtsueldo.setForeground(new java.awt.Color(0, 51, 102));
        txtsueldo.setText("sueldo");
        txtsueldo.setBorderColor(new java.awt.Color(0, 51, 102));
        txtsueldo.setColorIcon(new java.awt.Color(0, 51, 102));
        txtsueldo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MONETIZATION_ON);

        btneditar.setBackground(new java.awt.Color(0, 51, 102));
        btneditar.setText(" Actualizar");
        btneditar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtsueldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                            .addComponent(txtcargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtempresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txttelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcorre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(labelIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltIID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblrID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(labelIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltIID)
                            .addComponent(lblrID))
                        .addGap(31, 31, 31)))
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcorre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        NegocioClientes n1 = new NegocioClientes();
        
        EncapsulamientoClientes n2 = n1.mostrarCliente(id);
        lblrID.setText(""+ n2.getId());
        txtnombre.setText(n2.getNombre());
        txtcorre.setText(n2.getCorreo());
        txttelefono.setText(""+n2.getTelefono());
        txtdireccion.setText(n2.getDireccion());
        txtempresa.setText(n2.getEmpresa());
        txtcargo.setText(n2.getCargo());
        txtsueldo.setText(""+n2.getSueldo());
        
    }//GEN-LAST:event_formWindowOpened

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        EncapsulamientoClientes n1 = new EncapsulamientoClientes();
        n1.setId(Integer.parseInt(lblrID.getText()));
        
        n1.setNombres(txtnombre.getText());
        n1.setCorreo(txtcorre.getText());
        n1.setTelefono(Integer.parseInt(txttelefono.getText()));
        //         n1.setTelefono(Integer.parseInt(txttelefono.getText()));

        n1.setDireccion(txtdireccion.getText());
        n1.setEmpresa(txtempresa.getText());
        n1.setCargo(txtcargo.getText());
        n1.setSueldo(Integer.parseInt(txtsueldo.getText()));

        NegocioClientes n2 = new NegocioClientes();
        boolean resultado = n2.editarClientes(n1);
        
        if(resultado == true)
        {
            JOptionPane.showMessageDialog(null, "registro actualizado");
        }
        ModificacionClientes m1 = new ModificacionClientes();
        m1.show();
        this.dispose();

    }//GEN-LAST:event_btneditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne btneditar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private necesario.LabelIcon labelIcon1;
    private javax.swing.JLabel lblrID;
    private javax.swing.JLabel lbltIID;
    private RSMaterialComponent.RSTextFieldIconOne txtcargo;
    private RSMaterialComponent.RSTextFieldIconOne txtcorre;
    private RSMaterialComponent.RSTextFieldIconOne txtdireccion;
    private RSMaterialComponent.RSTextFieldIconOne txtempresa;
    private RSMaterialComponent.RSTextFieldIconOne txtnombre;
    private RSMaterialComponent.RSTextFieldIconOne txtsueldo;
    private RSMaterialComponent.RSTextFieldIconOne txttelefono;
    // End of variables declaration//GEN-END:variables
}
