/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autos;

import encapsulamiento.EncapsulamientoAutos;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.NegocioAutos;

/**
 *
 * @author Joakim
 */
public class ModificacionAutos extends javax.swing.JFrame {

    /**
     * Creates new form ModificacionNiveles
     */
    public ModificacionAutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableniveles = new javax.swing.JTable();
        btneliminar = new javax.swing.JButton();
        lblid = new javax.swing.JLabel();
        btneditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbltitulo.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lbltitulo.setText("Modificacion de Autos");

        tableniveles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "serie", "modelo", "año", "precio", "color"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableniveles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablenivelesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableniveles);

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        lblid.setText("jLabel1");

        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btneditar, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblid))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lbltitulo)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbltitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblid)
                        .addGap(48, 48, 48)
                        .addComponent(btneditar)
                        .addGap(57, 57, 57)
                        .addComponent(btneliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        
        if(tableniveles.getSelectedRowCount()== 0){
            JOptionPane.showMessageDialog(null, "Por favor seleccione una fila");
        return;
        }
        int id = (int)tableniveles.getValueAt(tableniveles.getSelectedRow(), 0);

        int res = 0;
        res = JOptionPane.showConfirmDialog(null, "estas seguro?");
        
        if(res == 0){
            NegocioAutos n1 =new NegocioAutos();
            boolean respuesta = n1.eliminarClientes(id);
            
            if (respuesta == true){
                JOptionPane.showMessageDialog(null, "el registro fue eliminados");
                RellenarTabla();
            }
        }
 
        
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
        if(tableniveles.getSelectedRowCount()== 0){
            JOptionPane.showMessageDialog(null, "Por favor seleccione una fila");
        return;
        }
                int id = (int)tableniveles.getValueAt(tableniveles.getSelectedRow(), 0);

        
        EditarAuto e1 = new EditarAuto();
        e1.id=id;
        e1.show();
        
        
    }//GEN-LAST:event_btneditarActionPerformed
public void RellenarTabla()
{
    NegocioAutos n1 = new NegocioAutos();
    List<EncapsulamientoAutos> listautos = n1.mostrarAutos();
    
    DefaultTableModel modeloTabla = (DefaultTableModel) tableniveles.getModel();
    
    while(modeloTabla.getRowCount()>0)
    {
        
    modeloTabla.removeRow(0);
    
    }
    
    for(EncapsulamientoAutos autos : listautos)
    {
       Object[] Datofila = 
        {
            autos.getId(),
            autos.getSerie(),
            autos.getModelo(),
            autos.getAno(),
            autos.getPrecio(),
            autos.getColor()
        };
       modeloTabla.addRow(Datofila);
    }
    tableniveles.setModel(modeloTabla);
}
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        RellenarTabla();
        
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void tablenivelesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablenivelesMouseClicked
        // TODO add your handling code here:
        int id = (int)tableniveles.getValueAt(tableniveles.getSelectedRow(), 0);
       lblid.setText("El id seleccionado es\n "+ id);
        
        
    }//GEN-LAST:event_tablenivelesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificacionAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificacionAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificacionAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificacionAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificacionAutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTable tableniveles;
    // End of variables declaration//GEN-END:variables
}
