/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PresentacionVendedores;

import encapsulamiento.EncapsulamientoNiveles;
import encapsulamiento.EncapsulamientoVendedores;
import java.util.List;
import javax.swing.JOptionPane;
import negocio.NegocioNiveles;
import negocio.NegocioVendedores;

/**
 *
 * @author Joakim
 */
public class EEEEeditarVendedores1 extends javax.swing.JFrame {

    /**
     * Creates new form editarNivel
     */
    public EEEEeditarVendedores1() {
        initComponents();
    }
    public void ComboBoxNiveles(){
        
        cbxniveles1.removeAllItems();
        NegocioNiveles n1 = new NegocioNiveles();
        List<EncapsulamientoNiveles>listaNiveles = n1.mostrarNiveles();
        for(EncapsulamientoNiveles nivel : listaNiveles){
           
            this.cbxniveles1.addItem(nivel.getId()+"-"+nivel.getDescripcion());
            
        }
    }
public  int id;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accelerateInterpolator1 = new rojeru_san.extras.AccelerateInterpolator();
        lbltIID = new javax.swing.JLabel();
        lblrID = new javax.swing.JLabel();
        txttelefono = new RSMaterialComponent.RSTextFieldIconOne();
        txtrfc = new RSMaterialComponent.RSTextFieldIconOne();
        txtnombre = new RSMaterialComponent.RSTextFieldIconOne();
        txtcorre = new RSMaterialComponent.RSTextFieldIconOne();
        cbxniveles1 = new RSMaterialComponent.RSComboBoxMaterial();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnaactu = new RSMaterialComponent.RSButtonMaterialIconOne();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbltIID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltIID.setText("ID:");

        lblrID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblrID.setText("jLabel1");

        txttelefono.setForeground(new java.awt.Color(0, 51, 102));
        txttelefono.setBorderColor(new java.awt.Color(0, 51, 102));
        txttelefono.setColorIcon(new java.awt.Color(0, 51, 102));
        txttelefono.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PHONE);
        txttelefono.setPlaceholder("Telefono");

        txtrfc.setForeground(new java.awt.Color(0, 51, 102));
        txtrfc.setBorderColor(new java.awt.Color(0, 51, 102));
        txtrfc.setColorIcon(new java.awt.Color(0, 51, 102));
        txtrfc.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        txtrfc.setPlaceholder("Rfc");

        txtnombre.setForeground(new java.awt.Color(0, 51, 102));
        txtnombre.setBorderColor(new java.awt.Color(0, 51, 102));
        txtnombre.setColorIcon(new java.awt.Color(0, 51, 102));
        txtnombre.setPlaceholder("Nombre");
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txtcorre.setForeground(new java.awt.Color(0, 51, 102));
        txtcorre.setBorderColor(new java.awt.Color(0, 51, 102));
        txtcorre.setColorIcon(new java.awt.Color(0, 51, 102));
        txtcorre.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MAIL);
        txtcorre.setPlaceholder("Correo");

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setForeground(new java.awt.Color(0, 51, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EDITAR VENDEDOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnaactu.setBackground(new java.awt.Color(0, 51, 102));
        btnaactu.setText(" Actualizar");
        btnaactu.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        btnaactu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaactuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbltIID)
                                .addGap(18, 18, 18)
                                .addComponent(lblrID)
                                .addGap(32, 32, 32))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbxniveles1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtrfc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                    .addComponent(txttelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtcorre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnaactu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblrID)
                    .addComponent(lbltIID))
                .addGap(11, 11, 11)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(txtcorre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtrfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxniveles1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnaactu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        NegocioVendedores n1 = new NegocioVendedores();
        
        EncapsulamientoVendedores n2 = n1.mostrarVendedor(id);
        lblrID.setText(""+ n2.getId());
        txtnombre.setText(n2.getNombre());
        txtcorre.setText(n2.getCorreo());
        txtrfc.setText(n2.getRfc());
        txttelefono.setText(""+n2.getTelefono());
        ComboBoxNiveles();
        
    }//GEN-LAST:event_formWindowOpened

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btnaactuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaactuActionPerformed

        // TODO add your handling code here:
        
        EncapsulamientoVendedores n1 = new EncapsulamientoVendedores();
           String nombreNivel = this.cbxniveles1.getSelectedItem().toString();
          String[] partes = nombreNivel.split("-");
          int idNivel = Integer.parseInt(partes[0]);
          n1.setNivel_id(idNivel);
          
        n1.setId(Integer.parseInt(lblrID.getText()));
        n1.setNombre(txtnombre.getText());
         n1.setCorreo(txtcorre.getText());
         n1.setTelefono(Integer.parseInt(txttelefono.getText()));
         n1.setRfc(txtrfc.getText());
         n1.setNivel_id(idNivel);

///        n1.setDescripcion(txtdescripcion.getText());

        NegocioVendedores n2 = new NegocioVendedores();
        boolean resultado = n2.editarVendedores(n1);
        
        if(resultado == true)
        {
            JOptionPane.showMessageDialog(null, "registro actualizado");
        }
        ModificacionVendedores m1 = new ModificacionVendedores();
        m1.show();
        this.dispose();        
    }//GEN-LAST:event_btnaactuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EEEEeditarVendedores1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EEEEeditarVendedores1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EEEEeditarVendedores1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EEEEeditarVendedores1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EEEEeditarVendedores1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.extras.AccelerateInterpolator accelerateInterpolator1;
    private RSMaterialComponent.RSButtonMaterialIconOne btnaactu;
    private RSMaterialComponent.RSComboBoxMaterial cbxniveles1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblrID;
    private javax.swing.JLabel lbltIID;
    private RSMaterialComponent.RSTextFieldIconOne txtcorre;
    private RSMaterialComponent.RSTextFieldIconOne txtnombre;
    private RSMaterialComponent.RSTextFieldIconOne txtrfc;
    private RSMaterialComponent.RSTextFieldIconOne txttelefono;
    // End of variables declaration//GEN-END:variables
}
