/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PresentacionVendedores;

import encapsulamiento.EncapsulamientoVendedores;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.NegocioVendedores;

/**
 *
 * @author Joakim
 */
public class ModificacionVendedores extends javax.swing.JFrame {

    /**
     * Creates new form ModificacionNiveles
     */
    public ModificacionVendedores() {
        initComponents();
    }
public String nombrelogin;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableniveles = new RSMaterialComponent.RSTableMetroCustom();
        btneliminar1 = new RSMaterialComponent.RSButtonMaterialIconOne();
        btneditar1 = new RSMaterialComponent.RSButtonMaterialIconOne();
        lblid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setForeground(new java.awt.Color(0, 51, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MODIFICAR VENDEDORES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tableniveles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "CORREO", "TELEFONO", "RFC", "NIVEL"
            }
        ));
        tableniveles.setBackgoundHead(new java.awt.Color(0, 51, 102));
        tableniveles.setBackgoundHover(new java.awt.Color(0, 51, 102));
        tableniveles.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tableniveles.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        tableniveles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablenivelesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableniveles);

        btneliminar1.setBackground(new java.awt.Color(0, 51, 102));
        btneliminar1.setText(" Eliminar");
        btneliminar1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REMOVE);
        btneliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar1ActionPerformed(evt);
            }
        });

        btneditar1.setBackground(new java.awt.Color(0, 51, 102));
        btneditar1.setText(" Editar");
        btneditar1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btneditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditar1ActionPerformed(evt);
            }
        });

        lblid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblid.setForeground(new java.awt.Color(51, 51, 51));
        lblid.setText("ID ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btneditar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btneliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblid)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btneditar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblid))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void RellenarTabla()
{
    NegocioVendedores n1 = new NegocioVendedores();
    List<EncapsulamientoVendedores> listNiveles = n1.MostrarVendedores();
    
    DefaultTableModel modeloTabla = (DefaultTableModel) tableniveles.getModel();
    
    while(modeloTabla.getRowCount()>0)
    {
        
    modeloTabla.removeRow(0);
    
    }
    
    for(EncapsulamientoVendedores nivel : listNiveles)
    {
       Object[] Datofila = 
        {
            nivel.getId(),
                nivel.getNombre(),
                nivel.getCorreo(),
                nivel.getTelefono(),
                nivel.getRfc(),
                nivel.getDescripcion(),
                nivel.getNivel_id()
        };
       modeloTabla.addRow(Datofila);
    }
    tableniveles.setModel(modeloTabla);
}
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        RellenarTabla();   
    }//GEN-LAST:event_formWindowOpened

    private void btneliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar1ActionPerformed
        // TODO add your handling code here:
        if(tableniveles.getSelectedRowCount()== 0){
            JOptionPane.showMessageDialog(null, "Por favor seleccione una fila");
            return;
        }
        int id = (int)tableniveles.getValueAt(tableniveles.getSelectedRow(), 0);

        int res = 0;
        res = JOptionPane.showConfirmDialog(null, "estas seguro?");

        if(res == 0){
            NegocioVendedores n1 = new NegocioVendedores();
            boolean respuesta = n1.eliminarVendedor(id);

            if (respuesta == true){
                JOptionPane.showMessageDialog(null, "el registro fue eliminados");
                RellenarTabla();
            }
        }
    }//GEN-LAST:event_btneliminar1ActionPerformed

    private void btneditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditar1ActionPerformed
        // TODO add your handling code here:
        if(tableniveles.getSelectedRowCount()== 0){
            JOptionPane.showMessageDialog(null, "Por favor seleccione una fila");
            return;
        }
        int id = (int)tableniveles.getValueAt(tableniveles.getSelectedRow(), 0);

        EEEEeditarVendedores1 e1 = new EEEEeditarVendedores1();
        e1.id=id;
        e1.show();
    }//GEN-LAST:event_btneditar1ActionPerformed

    private void tablenivelesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablenivelesMouseClicked
        // TODO add your handling code here:
         int id = (int)tableniveles.getValueAt(tableniveles.getSelectedRow(), 0);
       lblid.setText("ID "+ id);
    }//GEN-LAST:event_tablenivelesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificacionVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificacionVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificacionVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificacionVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificacionVendedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne btneditar1;
    private RSMaterialComponent.RSButtonMaterialIconOne btneliminar1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblid;
    private RSMaterialComponent.RSTableMetroCustom tableniveles;
    // End of variables declaration//GEN-END:variables
}
