/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventas;
import encapsulamiento.EncapsulamientoAutos;
import encapsulamiento.EncapsulamientoClientes;
import encapsulamiento.EncapsulamientoTiposdepago;
import encapsulamiento.EncapsulamientoVendedores;
import encapsulamiento.EncapsulamientoVentas;
import java.text.DateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import negocio.NegocioAutos;
import negocio.NegocioClientes;
import negocio.NegocioTiposdepago;
import negocio.NegocioVentas;
import negocio.NegocioVendedores;
/**
 *
 * @author Joakim
 */
public class CrearVenta extends javax.swing.JFrame {

    /**
     * Creates new form CrearVenta
     */
    public CrearVenta() {
        initComponents();
    }
    public void ComboBoxVendedores(){
        
        cbxvendedor.removeAllItems();
        NegocioVendedores n1 = new NegocioVendedores();
        List<EncapsulamientoVendedores>listaVendedores = n1.MostrarVendedores();
        for(EncapsulamientoVendedores vendedor : listaVendedores){
           
            this.cbxvendedor.addItem(vendedor.getId()+"-"+vendedor.getNombre());
            
        }
    }
    
     public void ComboBoxClientes(){
        
        cbxcliente.removeAllItems();
         NegocioClientes n1 = new NegocioClientes();
        List<EncapsulamientoClientes>listaclientes = n1.mostrarClientes();
        for(EncapsulamientoClientes cliente : listaclientes){
           
            this.cbxcliente.addItem(cliente.getId()+"-"+cliente.getNombre());
            
        }
    }
      public void ComboBoxAutos(){
        
        cbxauto.removeAllItems();
        NegocioAutos n1 = new NegocioAutos();
        List<EncapsulamientoAutos>listaAutos = n1.mostrarAutos();
        for(EncapsulamientoAutos autos : listaAutos){
           
            this.cbxauto.addItem(autos.getId()+"-"+autos.getModelo());
            
        }
    }
     public void ComboBoxpago(){
        
        cbxpago.removeAllItems();
         NegocioTiposdepago n1 = new NegocioTiposdepago();
        List<EncapsulamientoTiposdepago>listapagos = n1.mostrarPagos();
        for(EncapsulamientoTiposdepago pago : listapagos){
           
            this.cbxpago.addItem(pago.getId()+"-"+pago.getDescripcion());
            
        }
    }
     void fecha(){
         DateFormat df = DateFormat.getDateInstance();
         Date FechaActual = new Date();
         this.jfecha.setDate(FechaActual);
         txtfecha.setText(df.format(FechaActual));
         
     }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jfecha = new com.toedter.calendar.JDateChooser();
        cbxauto = new RSMaterialComponent.RSComboBox();
        cbxpago = new RSMaterialComponent.RSComboBox();
        txtfecha = new RSMaterialComponent.RSTextFieldIconOne();
        cbxcliente = new RSMaterialComponent.RSComboBox();
        cbxvendedor = new RSMaterialComponent.RSComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnañadir = new RSMaterialComponent.RSButtonMaterialIconOne();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jFormattedTextField1.setText("jFormattedTextField1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Vendedor");

        jLabel2.setText("Cliente");

        jLabel3.setText("Auto");

        jLabel4.setText("Fecha");

        jLabel5.setText("tipo de pago");

        cbxauto.setColorArrow(new java.awt.Color(0, 51, 102));
        cbxauto.setColorBorde(new java.awt.Color(0, 51, 102));
        cbxauto.setColorFondo(new java.awt.Color(0, 51, 102));
        cbxauto.setColorSeleccion(new java.awt.Color(0, 0, 102));

        cbxpago.setColorArrow(new java.awt.Color(0, 51, 102));
        cbxpago.setColorBorde(new java.awt.Color(0, 51, 102));
        cbxpago.setColorFondo(new java.awt.Color(0, 51, 102));
        cbxpago.setColorSeleccion(new java.awt.Color(0, 0, 102));

        txtfecha.setForeground(new java.awt.Color(0, 51, 102));
        txtfecha.setBorderColor(new java.awt.Color(0, 51, 102));
        txtfecha.setColorIcon(new java.awt.Color(0, 51, 102));
        txtfecha.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DATE_RANGE);
        txtfecha.setPlaceholder("Fecha");
        txtfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaActionPerformed(evt);
            }
        });

        cbxcliente.setColorArrow(new java.awt.Color(0, 51, 102));
        cbxcliente.setColorBorde(new java.awt.Color(0, 51, 102));
        cbxcliente.setColorFondo(new java.awt.Color(0, 51, 102));
        cbxcliente.setColorSeleccion(new java.awt.Color(0, 0, 102));

        cbxvendedor.setColorArrow(new java.awt.Color(0, 51, 102));
        cbxvendedor.setColorBorde(new java.awt.Color(0, 51, 102));
        cbxvendedor.setColorFondo(new java.awt.Color(0, 51, 102));
        cbxvendedor.setColorSeleccion(new java.awt.Color(0, 0, 102));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setForeground(new java.awt.Color(0, 51, 102));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Crear venta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnañadir.setBackground(new java.awt.Color(0, 51, 102));
        btnañadir.setText(" Crear");
        btnañadir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INSERT_DRIVE_FILE);
        btnañadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnañadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(42, 42, 42))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(36, 36, 36))
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jLabel2))
                                    .addGap(12, 12, 12)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxauto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnañadir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxauto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnañadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        ComboBoxVendedores();
        ComboBoxClientes();
        ComboBoxpago();
        ComboBoxAutos();
        fecha();
        jfecha.show(false);
    }//GEN-LAST:event_formWindowOpened

    private void txtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaActionPerformed

    private void btnañadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnañadirActionPerformed

        
                
                String nombrevendedor = this.cbxvendedor.getSelectedItem().toString();
                String[] partesV = nombrevendedor.split("-");
                int idvendedor = Integer.parseInt(partesV[0]);
                
                String nombrecliente = this.cbxcliente.getSelectedItem().toString();
                String[] partesC = nombrecliente.split("-");
                int idcliente = Integer.parseInt(partesC[0]);
                
                String nombreauto = this.cbxauto.getSelectedItem().toString();
                String[] partesA = nombreauto.split("-");
                int idAuto = Integer.parseInt(partesA[0]);

                String tipopago = this.cbxpago.getSelectedItem().toString();
                String[] partesP = tipopago.split("-");
                int idPago = Integer.parseInt(partesP[0]);


               
         String fecha = txtfecha.getText();
        EncapsulamientoVentas v1 = new EncapsulamientoVentas();
        v1.setVendedor_id(idvendedor);
        v1.setCliente_id(idcliente);
        v1.setAuto_id(idAuto);
        v1.setTipopago(tipopago);
        v1.setFecha(fecha);
        
        NegocioVentas n1= new NegocioVentas();
        String Respuesta = n1.crearVenta(v1);
        
        JOptionPane.showMessageDialog(null, Respuesta);
        
        
    }//GEN-LAST:event_btnañadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne btnañadir;
    private RSMaterialComponent.RSComboBox cbxauto;
    private RSMaterialComponent.RSComboBox cbxcliente;
    private RSMaterialComponent.RSComboBox cbxpago;
    private RSMaterialComponent.RSComboBox cbxvendedor;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jfecha;
    private RSMaterialComponent.RSTextFieldIconOne txtfecha;
    // End of variables declaration//GEN-END:variables
}
