/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventas;

import autos.*;
import encapsulamiento.EncapsulamientoVentas;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.NegocioVentas;

/**
 *
 * @author Joakim
 */
public class ModificacionVentas extends javax.swing.JFrame {

    /**
     * Creates new form ModificacionNiveles
     */
    public ModificacionVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableautos = new RSMaterialComponent.RSTableMetroCustom();
        btneliminar1 = new RSMaterialComponent.RSButtonMaterialIconOne();
        btneditar1 = new RSMaterialComponent.RSButtonMaterialIconOne();
        lblid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setForeground(new java.awt.Color(0, 51, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MODIFICAR VENTAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tableautos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "VENDEDOR", "CLIENTE", "AUTO", "PAGO", "FECHA", "PRECIO"
            }
        ));
        tableautos.setBackgoundHead(new java.awt.Color(0, 51, 102));
        tableautos.setBackgoundHover(new java.awt.Color(0, 51, 102));
        tableautos.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tableautos.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        tableautos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableautosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableautos);

        btneliminar1.setBackground(new java.awt.Color(0, 51, 102));
        btneliminar1.setText(" Eliminar");
        btneliminar1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REMOVE);
        btneliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar1ActionPerformed(evt);
            }
        });

        btneditar1.setBackground(new java.awt.Color(0, 51, 102));
        btneditar1.setText(" Editar");
        btneditar1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btneditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditar1ActionPerformed(evt);
            }
        });

        lblid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblid.setForeground(new java.awt.Color(51, 51, 51));
        lblid.setText("ID ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btneditar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btneliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblid)
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btneditar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void RellenarTabla()
{
    NegocioVentas n1 = new NegocioVentas();
    List<EncapsulamientoVentas> listautos = n1.mostrarVentas();
    
    DefaultTableModel modeloTabla = (DefaultTableModel) tableautos.getModel();
    
    while(modeloTabla.getRowCount()>0)
    {
        
    modeloTabla.removeRow(0);
    
    }
    
    for(EncapsulamientoVentas Venta : listautos)
    {
       Object[] Datofila = 
        {
            Venta.getId(),
            Venta.getVendenom(),
            Venta.getClientenom(),
            Venta.getAutomod(),
            Venta.getTipopago(),
            Venta.getFecha(),
            Venta.getPrecio()
            
        };
       modeloTabla.addRow(Datofila);
    }
    tableautos.setModel(modeloTabla);
}
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        RellenarTabla();
        
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btneliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar1ActionPerformed
            

                // TODO add your handling code here:
        
        if(tableautos.getSelectedRowCount()== 0){
            JOptionPane.showMessageDialog(null, "Por favor seleccione una fila");
        return;
        }
        int id = (int)tableautos.getValueAt(tableautos.getSelectedRow(), 0);

        int res = 0;
        res = JOptionPane.showConfirmDialog(null, "estas seguro?");
        
        if(res == 0){
            NegocioVentas n1 =new NegocioVentas();
            boolean respuesta = n1.eliminarVenta(id);
            
            if (respuesta == true){
                JOptionPane.showMessageDialog(null, "el registro fue eliminados");
                RellenarTabla();
            }
        }
 
        



    }//GEN-LAST:event_btneliminar1ActionPerformed

    private void btneditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditar1ActionPerformed
        // TODO add your handling code here:
        if(tableautos.getSelectedRowCount()== 0){
            JOptionPane.showMessageDialog(null, "Por favor seleccione una fila");
        return;
        }
                int id = (int)tableautos.getValueAt(tableautos.getSelectedRow(), 0);

        
        EditarVenta e1 = new EditarVenta();
        e1.id=id;
        e1.show();
        
       
        
        
        
        
        
    }//GEN-LAST:event_btneditar1ActionPerformed

    private void tableautosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableautosMouseClicked
        // TODO add your handling code here:
         int id = (int)tableautos.getValueAt(tableautos.getSelectedRow(), 0);
       lblid.setText("ID "+ id);
    }//GEN-LAST:event_tableautosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificacionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificacionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificacionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificacionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificacionVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne btneditar1;
    private RSMaterialComponent.RSButtonMaterialIconOne btneliminar1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblid;
    private RSMaterialComponent.RSTableMetroCustom tableautos;
    // End of variables declaration//GEN-END:variables
}
